@startuml
!theme plain
skinparam groupInheritance 1
skinparam linetype ortho

Equipamiento <|-- SinEquipamiento
Equipamiento <|-- Casco
Equipamiento <|-- Armadura
Equipamiento <|-- EscudoYEspada
Equipamiento <|-- Llave

SinEquipamiento ..> Casco
Casco ..> Armadura
Armadura ..> EscudoYEspada
EscudoYEspada ..> Llave

Class Equipamiento{
    + {abstract} actualizar() : Equipamiento
    + {abstract} resistirAtaque( :Gladiador)
    + {abstract} abrirPuerta( :Gladiador, :Camino)
}

class SinEquipamiento{
    + actualizar() : Equipamiento
    + resistirAtaque( :Gladiador)
    + abrirPuerta( :Gladiador, :Camino)
}

class Casco{
    + actualizar() : Equipamiento
    + resistirAtaque( :Gladiador)
    + abrirPuerta( :Gladiador, :Camino)
}

class Armadura{
    + actualizar() : Equipamiento
    + resistirAtaque( :Gladiador)
    + abrirPuerta( :Gladiador, :Camino)
}

class EscudoYEspada{
    + actualizar() : Equipamiento
    + resistirAtaque( :Gladiador)
    + abrirPuerta( :Gladiador, :Camino)
}

class Llave {
    + actualizar() : Equipamiento
    + resistirAtaque( :Gladiador)
    + abrirPuerta( :Gladiador, :Camino)
}


@enduml